updates:
  - # See documentation for possible values
    directory: / # Location of package manifests
    groups:
      auth:
        applies-to: version-updates
        patterns:
          - better-auth
      nextjs:
        applies-to: version-updates
        patterns:
          - '@next/*'
          - '@types/react'
          - '@types/react-dom'
          - eslint-config-next
          - next
      prisma:
        applies-to: version-updates
        patterns:
          - '@prisma/adapter-pg'
          - '@prisma/client'
          - prisma
      tailwindcss:
        applies-to: version-updates
        patterns:
          - '@tailwindcss/postcss'
          - tailwindcss
    ignore:
      - dependency-name: '@aws-sdk/client-lambda'
      - dependency-name: '@aws-sdk/client-s3'
      - dependency-name: '@aws-sdk/s3-request-presigner'
      - dependency-name: sharp
      - dependency-name: '@types/node'
      - dependency-name: '@types/react'
      - dependency-name: react
      - dependency-name: react-dom
    open-pull-requests-limit: 20
    package-ecosystem: npm # See documentation for possible values
    schedule:
      interval: weekly
version: 2
