// all chatgpt generated could be errors
export const SEED_1800 = {
  'Consumer Goods': {
    category: 'Consumer Good',
    icon: 'empty',
    items: [
      { name: 'Fish', icon: 'empty' },
      { name: 'Schnapps', icon: 'empty' },
      { name: 'Work Clothes', icon: 'empty' },
      { name: 'Sausages', icon: 'empty' },
      { name: 'Bread', icon: 'empty' },
      { name: 'Soap', icon: 'empty' },
      { name: 'Beer', icon: 'empty' },
      { name: 'Canned Food', icon: 'empty' },
      { name: 'Sewing Machines', icon: 'empty' },
      { name: 'Rum', icon: 'empty' },
      { name: 'Fur Coats', icon: 'empty' },
      { name: 'Glasses', icon: 'empty' },
      { name: 'Penny Farthings', icon: 'empty' },
      { name: 'Pocket Watches', icon: 'empty' },
      { name: 'Coffee', icon: 'empty' },
      { name: 'Light Bulbs', icon: 'empty' },
      { name: 'Jam', icon: 'empty' },
      { name: 'Shampoo', icon: 'empty' },
      { name: 'Lemonade', icon: 'empty' },
      { name: 'Souvenirs', icon: 'empty' },
      { name: 'Champagne', icon: 'empty' },
      { name: 'Cigars', icon: 'empty' },
      { name: 'Chocolate', icon: 'empty' },
      { name: 'Jewellery', icon: 'empty' },
      { name: 'Gramophones', icon: 'empty' },
      { name: 'Steam Carriages', icon: 'empty' },
      { name: 'Leather Boots', icon: 'empty' },
      { name: 'Tailored Suits', icon: 'empty' },
      { name: 'Bowler Hats', icon: 'empty' },
      { name: 'Hibiscus Tea', icon: 'empty' },
      { name: 'Seafood Stew', icon: 'empty' },
      { name: 'Tapestries', icon: 'empty' },
      { name: 'Clay Pipes', icon: 'empty' },
      { name: 'Telephones', icon: 'empty' },
      { name: 'Fried Plantains', icon: 'empty' },
      { name: 'Ponchos', icon: 'empty' },
      { name: 'Tortillas', icon: 'empty' },
      { name: 'Pemmican', icon: 'empty' },
      { name: 'Oil Lamps', icon: 'empty' },
      { name: 'Sleeping Bags', icon: 'empty' },
      { name: 'Parkas', icon: 'empty' },
      { name: 'Husky Sleds', icon: 'empty' },
      { name: 'Goat Milk', icon: 'empty' },
      { name: 'Finery', icon: 'empty' },
      { name: 'Dried Meat', icon: 'empty' },
      { name: 'Ceramics', icon: 'empty' },
      { name: 'Illuminated Script', icon: 'empty' },
      { name: 'Lanterns', icon: 'empty' },
      { name: 'Chewing Gum', icon: 'empty' },
      { name: 'Typewriters', icon: 'empty' },
      { name: 'Violins', icon: 'empty' },
      { name: 'Biscuits', icon: 'empty' },
      { name: 'Cognac', icon: 'empty' },
      { name: 'Billiard Tables', icon: 'empty' },
      { name: 'Toys', icon: 'empty' },
      { name: 'Atole', icon: 'empty' },
      { name: 'Hot Sauce', icon: 'empty' },
      { name: 'Soccer Balls', icon: 'empty' },
      { name: 'Mezcal', icon: 'empty' },
      { name: 'Jalea', icon: 'empty' },
      { name: 'Ice Cream', icon: 'empty' },
      { name: 'Perfumes', icon: 'empty' },
      { name: 'Fans', icon: 'empty' },
      { name: 'Scooter', icon: 'empty' },
    ],
  },
  'Construction Material': {
    category: 'Construction Material',
    icon: 'empty',
    items: [
      { name: 'Timber', icon: 'empty' },
      { name: 'Bricks', icon: 'empty' },
      { name: 'Sails', icon: 'empty' },
      { name: 'Steel Beams', icon: 'empty' },
      { name: 'Weapons', icon: 'empty' },
      { name: 'Windows', icon: 'empty' },
      { name: 'Reinforced Concrete', icon: 'empty' },
      { name: 'Steam Motors', icon: 'empty' },
      { name: 'Advanced Weapons', icon: 'empty' },
      { name: 'Arctic Gas', icon: 'empty' },
      { name: 'Wanza Timber', icon: 'empty' },
      { name: 'Mud Bricks', icon: 'empty' },
      { name: 'Elevators', icon: 'empty' },
      { name: 'Aluminium Profiles', icon: 'empty' },
      { name: 'Helium', icon: 'empty' },
    ],
  },
  'Raw Material': {
    category: 'Raw Material',
    icon: 'empty',
    items: [
      { name: 'Wood', icon: 'empty' },
      { name: 'Clay', icon: 'empty' },
      { name: 'Iron', icon: 'empty' },
      { name: 'Coal', icon: 'empty' },
      { name: 'Quartz Sand', icon: 'empty' },
      { name: 'Cement', icon: 'empty' },
      { name: 'Copper', icon: 'empty' },
      { name: 'Zinc', icon: 'empty' },
      { name: 'Saltpetre', icon: 'empty' },
      { name: 'Pearls', icon: 'empty' },
      { name: 'Gold Ore', icon: 'empty' },
      { name: 'Bauxite', icon: 'empty' },
      { name: 'Minerals', icon: 'empty' },
    ],
  },
  'Agricultural Products': {
    category: 'Agricultural Products',
    icon: 'empty',
    items: [
      { name: 'Potatoes', icon: 'empty' },
      { name: 'Wool', icon: 'empty' },
      { name: 'Pigs', icon: 'empty' },
      { name: 'Grain', icon: 'empty' },
      { name: 'Hops', icon: 'empty' },
      { name: 'Beef', icon: 'empty' },
      { name: 'Red Peppers', icon: 'empty' },
      { name: 'Furs', icon: 'empty' },
      { name: 'Cinnamon', icon: 'empty' },
      { name: 'Coconut Oil', icon: 'empty' },
      { name: 'Citrus', icon: 'empty' },
      { name: 'Camphor Wax', icon: 'empty' },
      { name: 'Grapes', icon: 'empty' },
      { name: 'Cherry Wood', icon: 'empty' },
      { name: 'Resin', icon: 'empty' },
      { name: 'Fish Oil', icon: 'empty' },
      { name: 'Plantains', icon: 'empty' },
      { name: 'Sugar Cane', icon: 'empty' },
      { name: 'Cotton', icon: 'empty' },
      { name: 'Alpaca Wool', icon: 'empty' },
      { name: 'Caoutchouc', icon: 'empty' },
      { name: 'Corn', icon: 'empty' },
      { name: 'Coffee Beans', icon: 'empty' },
      { name: 'Tobacco', icon: 'empty' },
      { name: 'Cocoa', icon: 'empty' },
      { name: 'Whale Oil', icon: 'empty' },
      { name: 'Caribou Meat', icon: 'empty' },
      { name: 'Seal Skin', icon: 'empty' },
      { name: 'Goose Feathers', icon: 'empty' },
      { name: 'Bear Fur', icon: 'empty' },
      { name: 'Huskies', icon: 'empty' },
      { name: 'Sanga Cow', icon: 'empty' },
      { name: 'Salt', icon: 'empty' },
      { name: 'Linseed', icon: 'empty' },
      { name: 'Hibiscus Petals', icon: 'empty' },
      { name: 'Teff', icon: 'empty' },
      { name: 'Indigo Dye', icon: 'empty' },
      { name: 'Lobster', icon: 'empty' },
      { name: 'Spices', icon: 'empty' },
      { name: 'Beeswax', icon: 'empty' },
      { name: 'Dung', icon: 'empty' },
      { name: 'Fertiliser', icon: 'empty' },
      { name: 'Nandu Leather', icon: 'empty' },
      { name: 'Herbs', icon: 'empty' },
      { name: 'Calamari', icon: 'empty' },
      { name: 'Milk', icon: 'empty' },
      { name: 'Orchid', icon: 'empty' },
      { name: 'Nandu Feathers', icon: 'empty' },
    ],
  },
  'Intermediate Products': {
    category: 'Intermediate Products',
    icon: 'empty',
    items: [
      { name: 'Flour', icon: 'empty' },
      { name: 'Steel', icon: 'empty' },
      { name: 'Tallow', icon: 'empty' },
      { name: 'Malt', icon: 'empty' },
      { name: 'Glass', icon: 'empty' },
      { name: 'Goulash', icon: 'empty' },
      { name: 'Brass', icon: 'empty' },
      { name: 'Steam Motors', icon: 'empty' },
      { name: 'Gold', icon: 'empty' },
      { name: 'Filaments', icon: 'empty' },
      { name: 'Dynamite', icon: 'empty' },
      { name: 'Wood Veneers', icon: 'empty' },
      { name: 'Chassis', icon: 'empty' },
      { name: 'Cotton Fabric', icon: 'empty' },
      { name: 'Felt', icon: 'empty' },
      { name: 'Sugar', icon: 'empty' },
      { name: 'Ethanol', icon: 'empty' },
      { name: 'Celluloid', icon: 'empty' },
      { name: 'Lacquer', icon: 'empty' },
      { name: 'Industrial Lubricant', icon: 'empty' },
      { name: 'Sleds', icon: 'empty' },
      { name: 'Linen', icon: 'empty' },
      { name: 'Spiced Flour', icon: 'empty' },
      { name: 'Paper', icon: 'empty' },
      { name: 'Ornate Candles', icon: 'empty' },
      { name: 'Pigments', icon: 'empty' },
      { name: 'Costumes', icon: 'empty' },
      { name: 'Fire Extinguishers', icon: 'empty' },
      { name: 'Police Equipment', icon: 'empty' },
      { name: 'Film Reel', icon: 'empty' },
      { name: 'Electric Cables', icon: 'empty' },
      { name: 'Motor', icon: 'empty' },
      { name: 'Medicine', icon: 'empty' },
    ],
  },
}

const FARMERS = ['Wood', 'Fish', 'Potato', 'Schnapps', 'Wool', 'Work Clothes']

const WORKERS = [
  'Clay',
  'Bricks',
  'Pigs',
  'Sausages',
  'Grain',
  'Flour',
  'Bread',
  'Sails',
  'Coal',
  'Iron',
  'Steel',
  'Steel Beams',
  'Tallow',
  'Soap',
  'Weapons',
  'Hops',
  'Malt',
  'Beer',
]

const ARTISANS = [
  'Sand',
  'Glass',
  'Windows',
  'Beef',
  'Red Peppers',
  'Goulash',
  'Canned Food',
  'Sewing Machines',
  'Hunting Cabin',
  'Fur Coats',
]

const ENGINEERS = [
  'Cement',
  'Reinforced Concrete',
  'Copper',
  'Zinc',
  'Brass',
  'Glasses',
  'Dynamite',
  'Saltpetre',
  'Advanced Weapons',
  'Penny Farthings',
  'Steam Motors',
  'Gold',
  'Pocket Watches',
  'Filaments',
  'Light Bulbs',
]

const TOURISTS = ['Jam', 'Shampoo', 'Lemonade', 'Souvenirs']

const INVESTORS = [
  'Wine',
  'Champagne',
  'Jewellery',
  'Wood Veneers',
  'Gramophones',
  'Chassis',
  'Steam Carriages',
]
const SCHOLARS = [
  'Leather Boots',
  'Tailored Suits',
  'Telephones',
  'Advanced Coffee',
  'Advanced Rum',
  'Advanced Cotton Fabric',
]
const SKYSCRAPERS = [
  'Elevators',
  'Chewing Gum',
  'Biscuits',
  'Cognac',
  'Ethanol',
  'Celluloid',
  'Lacquer',
  'Typewriters',
  'Billiard Tables',
  'Violins',
  'Toys',
]

export const OLD_WORLD_GOODS = [
  ...FARMERS,
  ...WORKERS,
  ...ARTISANS,
  ...ENGINEERS,
  ...INVESTORS,
  ...TOURISTS,
  ...SCHOLARS,
  ...SKYSCRAPERS,
] as const

const JORNALEROS = [
  'Plantain',
  'Fish Oil',
  'Sugar Cane',
  'Fried Plantains',
  'Rum',
  'Alpaca Wool',
  'Ponchos',
  'Cotton',
  'Cotton Fabric',
  'Caoutchouc',
  'Pearls',
]

const OBREROS = [
  'Corn',
  'Tortillas',
  'Coffee Beans',
  'Coffee',
  'Felt',
  'Bowler Hats',
  'Tobacco',
  'Cigars',
  'Sugar',
  'Cocoa',
  'Chocolate',
  'Gold Ore',
  'Bauxite',
  'Aluminium Profiles',
]

const ARTISTAS = [
  'Nandu Leather',
  'Soccer Balls',
  'Citrus',
  'Herbs',
  'Mezcal',
  'Calamari',
  'Jalea',
  'Milk',
  'Ice Cream',
  'Fire Extinguishers',
  'Fire Department',
  'Orchid',
  'Ethanol',
  'Coconut Oil',
  'Perfumes',
  'Minerals',
  'Pigments',
  'Samba School',
  'Nandu Feathers',
  'Costumes',
  'Camphor Wax',
  'Celluloid',
  'Police Headquarters',
  'Motor',
  'Electric Cables',
  'Fans',
  'Film Reel',
  'Medicine',
  'Cinema',
  'City Hospital',
  'Scooter',
]
export const NEW_WORLD_GOODS = [...JORNALEROS, ...OBREROS, ...ARTISTAS]

const EXPLORERS = [
  'Whale Oil',
  'Caribou Meat',
  'Pemmican',
  'Seal Skin',
  'Goose Feathers',
  'Sleeping Bags',
  'Oil Lamps',
]

const TECHNICIANS = ['Bear Fur', 'Parkas', 'Sleds', 'Huskies', 'Husky Sleds']

export const ARCTIC_GOODS = [...EXPLORERS, ...TECHNICIANS]

const SHEPHERDS = [
  'Wanza Timber',
  'Goat Milk',
  'Finery',
  'Dried Meat',
  'Hibiscus Tea',
  'Sanga Cow',
  'Linseed',
  'Linen',
]

const ELDERS = [
  'Mud Bricks',
  'Ceramics',
  'Tapestries',
  'Seafood Stew',
  'Clay Pipes',
  'Illuminated Script',
  'Lanterns',
]

export const ENBESA_GOODS = [...SHEPHERDS, ...ELDERS]
