import { CreateStamp } from 'types'

import { Region1800 } from './enum'
export interface CreateStamp1800 extends CreateStamp {
  game: '1800'
  region: Region1800
}

// all chatgpt generated could be errors
// export type ConsumerGoods =
//   | 'Fish'
//   | 'Schnapps'
//   | 'Work Clothes'
//   | 'Sausages'
//   | 'Bread'
//   | 'Soap'
//   | 'Beer'
//   | 'Canned Food'
//   | 'Sewing Machines'
//   | 'Rum'
//   | 'Fur Coats'
//   | 'Glasses'
//   | 'Penny Farthings'
//   | 'Pocket Watches'
//   | 'Coffee'
//   | 'Light Bulbs'
//   | 'Jam'
//   | 'Shampoo'
//   | 'Lemonade'
//   | 'Souvenirs'
//   | 'Champagne'
//   | 'Cigars'
//   | 'Chocolate'
//   | 'Jewellery'
//   | 'Gramophones'
//   | 'Steam Carriages'
//   | 'Leather Boots'
//   | 'Tailored Suits'
//   | 'Bowler Hats'
//   | 'Hibiscus Tea'
//   | 'Seafood Stew'
//   | 'Tapestries'
//   | 'Clay Pipes'
//   | 'Telephones'
//   | 'Fried Plantains'
//   | 'Ponchos'
//   | 'Tortillas'
//   | 'Pemmican'
//   | 'Oil Lamps'
//   | 'Sleeping Bags'
//   | 'Parkas'
//   | 'Husky Sleds'
//   | 'Goat Milk'
//   | 'Finery'
//   | 'Dried Meat'
//   | 'Ceramics'
//   | 'Illuminated Script'
//   | 'Lanterns'
//   | 'Chewing Gum'
//   | 'Typewriters'
//   | 'Violins'
//   | 'Biscuits'
//   | 'Cognac'
//   | 'Billiard Tables'
//   | 'Toys'
//   | 'Atole'
//   | 'Hot Sauce'
//   | 'Soccer Balls'
//   | 'Mezcal'
//   | 'Jalea'
//   | 'Ice Cream'
//   | 'Perfumes'
//   | 'Fans'
//   | 'Scooter'

// export type ConstructionMaterials =
//   | 'Timber'
//   | 'Bricks'
//   | 'Sails'
//   | 'Steel Beams'
//   | 'Weapons'
//   | 'Windows'
//   | 'Reinforced Concrete'
//   | 'Steam Motors'
//   | 'Advanced Weapons'
//   | 'Arctic Gas'
//   | 'Wanza Timber'
//   | 'Mud Bricks'
//   | 'Elevators'
//   | 'Aluminium Profiles'
//   | 'Helium'

// export type RawMaterials =
//   | 'Wood'
//   | 'Clay'
//   | 'Iron'
//   | 'Coal'
//   | 'Quartz Sand'
//   | 'Cement'
//   | 'Copper'
//   | 'Zinc'
//   | 'Saltpetre'
//   | 'Pearls'
//   | 'Gold Ore'
//   | 'Bauxite'
//   | 'Minerals'

// export type AgriculturalProducts =
//   | 'Potatoes'
//   | 'Wool'
//   | 'Pigs'
//   | 'Grain'
//   | 'Hops'
//   | 'Beef'
//   | 'Red Peppers'
//   | 'Furs'
//   | 'Cinnamon'
//   | 'Coconut Oil'
//   | 'Citrus'
//   | 'Camphor Wax'
//   | 'Grapes'
//   | 'Cherry Wood'
//   | 'Resin'
//   | 'Fish Oil'
//   | 'Plantains'
//   | 'Sugar Cane'
//   | 'Cotton'
//   | 'Alpaca Wool'
//   | 'Caoutchouc'
//   | 'Corn'
//   | 'Coffee Beans'
//   | 'Tobacco'
//   | 'Cocoa'
//   | 'Whale Oil'
//   | 'Caribou Meat'
//   | 'Seal Skin'
//   | 'Goose Feathers'
//   | 'Bear Fur'
//   | 'Huskies'
//   | 'Sanga Cow'
//   | 'Salt'
//   | 'Linseed'
//   | 'Hibiscus Petals'
//   | 'Teff'
//   | 'Indigo Dye'
//   | 'Lobster'
//   | 'Spices'
//   | 'Beeswax'
//   | 'Dung'
//   | 'Fertiliser'
//   | 'Nandu Leather'
//   | 'Herbs'
//   | 'Calamari'
//   | 'Milk'
//   | 'Orchid'
//   | 'Nandu Feathers'

// export type IntermediateProducts =
//   | 'Flour'
//   | 'Steel'
//   | 'Tallow'
//   | 'Malt'
//   | 'Glass'
//   | 'Goulash'
//   | 'Brass'
//   | 'Steam Motors'
//   | 'Gold'
//   | 'Filaments'
//   | 'Dynamite'
//   | 'Wood Veneers'
//   | 'Chassis'
//   | 'Cotton Fabric'
//   | 'Felt'
//   | 'Sugar'
//   | 'Ethanol'
//   | 'Celluloid'
//   | 'Lacquer'
//   | 'Industrial Lubricant'
//   | 'Sleds'
//   | 'Linen'
//   | 'Spiced Flour'
//   | 'Paper'
//   | 'Ornate Candles'
//   | 'Pigments'
//   | 'Costumes'
//   | 'Fire Extinguishers'
//   | 'Police Equipment'
//   | 'Film Reel'
//   | 'Electric Cables'
//   | 'Motor'
//   | 'Medicine'

// export type GoodCategory =
//   | 'Consumer Good'
//   | 'Construction Material'
//   | 'Raw Material'
//   | 'Agricultural Products'
//   | 'Intermediate Products'

// export type OldWorldGoods =
//   | Farmers
//   | Workers
//   | Artisans
//   | Engineers
//   | Investors
//   | Scholars
//   | Tourists

// export type NewWorldGoods = Jornalero | Obrero | Artistas
// export type ArcticGoods = Explorers | Technicians
// export type EnbesaGoods = Shepherds | Elders
// export type Farmers =
//   | 'Wood'
//   | 'Fish'
//   | 'Potato'
//   | 'Schnapps'
//   | 'Wool'
//   | 'Work Clothes'

// export type Workers =
//   | 'Clay'
//   | 'Bricks'
//   | 'Pigs'
//   | 'Sausages'
//   | 'Grain'
//   | 'Flour'
//   | 'Bread'
//   | 'Sails'
//   | 'Coal'
//   | 'Iron'
//   | 'Steel'
//   | 'Steel Beams'
//   | 'Tallow'
//   | 'Soap'
//   | 'Weapons'
//   | 'Hops'
//   | 'Malt'
//   | 'Beer'

// export type Artisans =
//   | 'Sand'
//   | 'Glass'
//   | 'Windows'
//   | 'Beef'
//   | 'Red Peppers'
//   | 'Goulash'
//   | 'Canned Food'
//   | 'Sewing Machines'
//   | 'Hunting Cabin'
//   | 'Fur Coats'

// export type Engineers =
//   | 'Cement'
//   | 'Reinforced Concrete'
//   | 'Copper'
//   | 'Zinc'
//   | 'Brass'
//   | 'Glasses'
//   | 'Dynamite'
//   | 'Saltpetre'
//   | 'Advanced Weapons'
//   | 'Penny Farthings'
//   | 'Steam Motors'
//   | 'Gold'
//   | 'Pocket Watches'
//   | 'Filaments'
//   | 'Light Bulbs'

// export type Tourists = 'Jam' | 'Shampoo' | 'Lemonade' | 'Souvenirs'

// export type Investors =
//   | 'Wine'
//   | 'Champagne'
//   | 'Jewellery'
//   | 'Wood Veneers'
//   | 'Gramophones'
//   | 'Chassis'
//   | 'Steam Carriages'
// export type Skyscrapers =
//   | 'Elevators'
//   | 'Chewing Gum'
//   | 'Biscuits'
//   | 'Cognac'
//   | 'Ethanol'
//   | 'Celluloid'
//   | 'Lacquer'
//   | 'Typewriters'
//   | 'Billiard Tables'
//   | 'Violins'
//   | 'Toys'
// export type Scholars =
//   | 'Leather Boots'
//   | 'Tailored Suits'
//   | 'Telephones'
//   | 'Advanced Coffee'
//   | 'Advanced Rum'
//   | 'Advanced Cotton Fabric'
// export type Jornalero =
//   | 'Plantain'
//   | 'Fish Oil'
//   | 'Sugar Cane'
//   | 'Fried Plantains'
//   | 'Rum'
//   | 'Alpaca Wool'
//   | 'Ponchos'
//   | 'Cotton'
//   | 'Cotton Fabric'
//   | 'Caoutchouc'
//   | 'Pearls'
// export type Obrero =
//   | 'Corn'
//   | 'Tortillas'
//   | 'Coffee Beans'
//   | 'Coffee'
//   | 'Felt'
//   | 'Bowler Hats'
//   | 'Tobacco'
//   | 'Cigars'
//   | 'Sugar'
//   | 'Cocoa'
//   | 'Chocolate'
//   | 'Gold Ore'
// export type Artistas =
//   | 'Soccer Balls'
//   | 'Mezcal'
//   | 'Jalea'
//   | 'Ice Cream'
//   | 'Fire Department'
//   | 'Perfumes'
//   | 'Samba School'
//   | 'Police Headquarters'
//   | 'Fans'
//   | 'Cinema'
//   | 'City Hospital'
//   | 'Scooter'
// export type Explorers =
//   | 'Whale Oil'
//   | 'Caribou Meat'
//   | 'Pemmican'
//   | 'Seal Skin'
//   | 'Goose Feathers'
//   | 'Sleeping Bags'
//   | 'Oil Lamps'
// export type Technicians =
//   | 'Bear Fur'
//   | 'Parkas'
//   | 'Sleds'
//   | 'Huskies'
//   | 'Husky Sleds'
// export type Shepherds =
//   | 'Wanza Timber'
//   | 'Goat Milk'
//   | 'Finery'
//   | 'Dried Meat'
//   | 'Hibiscus Tea'
//   | 'Sanga Cow'
//   | 'Linseed'
//   | 'Linen'
// export type Elders =
//   | 'Mud Bricks'
//   | 'Ceramics'
//   | 'Tapestries'
//   | 'Seafood Stew'
//   | 'Clay Pipes'
//   | 'Illuminated Script'
//   | 'Lanterns'

// export type Tier =
//   | 'Farmers'
//   | 'Workers'
//   | 'Artisans'
//   | 'Engineers'
//   | 'Tourists'
//   | 'Investors'
//   | 'Skyscrapers'
//   | 'Scholars'
//   | 'Jornaleros'
//   | 'Obreros'
//   | 'Artistas'
//   | 'Explorers'
//   | 'Technicians'
//   | 'Shepherds'
//   | 'Elders'

// type Region = 'Old World' | 'New World' | 'Arctic' | 'Enbesa'

// interface ProductionItemData {
//   produces: ProductionItem[]
//   tier: Tier
// }

// interface RegionData {
//   contains: ProductionItemData[]
//   region: Region
// }
